// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_6tvwSGW-fjDvJl0CraP-ipqTKzz6B-s',
    appId: '1:425694976791:web:916b2143bb9edeec917552',
    messagingSenderId: '425694976791',
    projectId: 'proyecto-movil-incitech-ua',
    authDomain: 'proyecto-movil-incitech-ua.firebaseapp.com',
    storageBucket: 'proyecto-movil-incitech-ua.firebasestorage.app',
    measurementId: 'G-TZZB81L67T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-SpMm84g4lekvNs0RjjWnor3-yityRbY',
    appId: '1:425694976791:android:ff2fadd004942bee917552',
    messagingSenderId: '425694976791',
    projectId: 'proyecto-movil-incitech-ua',
    storageBucket: 'proyecto-movil-incitech-ua.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjEEj5GI-AeKZW2BkNoaSNz0iwEaGf7_Y',
    appId: '1:425694976791:ios:bc062aa82518609c917552',
    messagingSenderId: '425694976791',
    projectId: 'proyecto-movil-incitech-ua',
    storageBucket: 'proyecto-movil-incitech-ua.firebasestorage.app',
    iosBundleId: 'com.example.myAppIncitechUa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjEEj5GI-AeKZW2BkNoaSNz0iwEaGf7_Y',
    appId: '1:425694976791:ios:bc062aa82518609c917552',
    messagingSenderId: '425694976791',
    projectId: 'proyecto-movil-incitech-ua',
    storageBucket: 'proyecto-movil-incitech-ua.firebasestorage.app',
    iosBundleId: 'com.example.myAppIncitechUa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_6tvwSGW-fjDvJl0CraP-ipqTKzz6B-s',
    appId: '1:425694976791:web:d4fcbd0d10330d3e917552',
    messagingSenderId: '425694976791',
    projectId: 'proyecto-movil-incitech-ua',
    authDomain: 'proyecto-movil-incitech-ua.firebaseapp.com',
    storageBucket: 'proyecto-movil-incitech-ua.firebasestorage.app',
    measurementId: 'G-WLCZ91XYR3',
  );

}